### ISSUE TITLE
Reloadium plugin loading error

### ISSUE THREAD

**Issue by dkrystki** [reloadware/reloadium#137]
### Discussed in https://github.com/reloadware/reloadium/discussions/135

<div type='discussions-op-text'>

<sup>Originally posted by **praveensivasamy** April 15, 2023</sup>
Dears,

I am using Reloadium plugin in Pycharm. I get the following errors and the hot reloading stops working. My program is based on Python 3.8 version.

Has anyone come across this error by anychance ?

Stacktrace:

2023-04-15 13:27:00,874 [ 127024] SEVERE - #c.i.u.c.SchedulingWrapper - PyCharm 2023.1  Build #PC-231.8109.197
2023-04-15 13:27:00,874 [ 127024] SEVERE - #c.i.u.c.SchedulingWrapper - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-04-15 13:27:00,874 [ 127024] SEVERE - #c.i.u.c.SchedulingWrapper - OS: Windows 10
2023-04-15 13:27:00,874 [ 127024] SEVERE - #c.i.u.c.SchedulingWrapper - Plugin to blame: Reloadium - Hot Reloading & Profiling for Python version: 1.0.1
2023-04-15 13:27:00,875 [ 127025]   INFO - STDERR - Exception in thread "ApplicationImpl pooled thread 14" java.lang.AssertionError: org/apache/maven/artifact/versioning/ComparableVersion
2023-04-15 13:27:00,876 [ 127026]   INFO - STDERR - 	at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:54)
2023-04-15 13:27:00,876 [ 127026]   INFO - STDERR - 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:240)
2023-04-15 13:27:00,876 [ 127026]   INFO - STDERR - 	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.setException(SchedulingWrapper.java:288)
2023-04-15 13:27:00,876 [ 127026]   INFO - STDERR - 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2023-04-15 13:27:00,876 [ 127026]   INFO - STDERR - 	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
2023-04-15 13:27:00,876 [ 127026]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-04-15 13:27:00,876 [ 127026]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-04-15 13:27:00,876 [ 127026]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
2023-04-15 13:27:00,877 [ 127027]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
2023-04-15 13:27:00,877 [ 127027]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2023-04-15 13:27:00,877 [ 127027]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
2023-04-15 13:27:00,877 [ 127027]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-04-15 13:27:00,877 [ 127027]   INFO - STDERR - Caused by: java.lang.NoClassDefFoundError: org/apache/maven/artifact/versioning/ComparableVersion
2023-04-15 13:27:00,877 [ 127027]   INFO - STDERR - 	at rw.pkg.PackageManager.shouldInstall(PackageManager.java:140)
2023-04-15 13:27:00,877 [ 127027]   INFO - STDERR - 	at rw.service.Service.checkIfStillGood(Service.java:63)
2023-04-15 13:27:00,877 [ 127027]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2023-04-15 13:27:00,877 [ 127027]   INFO - STDERR - 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
2023-04-15 13:27:00,877 [ 127027]   INFO - STDERR - 	... 8 more
2023-04-15 13:27:00,877 [ 127027]   INFO - STDERR - Caused by: java.lang.ClassNotFoundException: org.apache.maven.artifact.versioning.ComparableVersion PluginClassLoader(plugin=PluginDescriptor(name=Reloadium - Hot Reloading & Profiling for Python, id=org.reloadium, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharmCE2023.1\plugins\reloadium, version=1.0.1, package=null, isBundled=false), packagePrefix=null, instanceId=30, state=active)
2023-04-15 13:27:00,877 [ 127027]   INFO - STDERR - 	... 12 more</div>

**Comment by dkrystki** [comment]
Fixed in Reloadium 1.1.0 and PyCharm plugin 1.1.0
