### ISSUE TITLE
MacOS M1, running Python 3.9 but Reloadium says version is not supported

### ISSUE THREAD

**Issue by SHxKM** [reloadware/reloadium#144]
## Describe the bug*
If I understand the error message correctly, Reloadium should support 3.9.x on MacOS M1. However, I'm getting the unsupported platform exception upon launching with the Debug button.

## Desktop or remote (please complete the following information):**
 - OS: MacOS
 - OS version: 13.0 (22A380)
 - M1 chip: yes
 - Reloadium package version: 0.9.5 (?)
 - PyCharm plugin version: 0.9.5
 - Editor: PyCharm
 - Python Version: 3.9.11
 - Python Architecture: 64BIT
 - Run mode: DEBUG

## Additional context
exception:

```
Traceback (most recent call last):
  File "/Users/me/.pyenv/versions/3.9.11/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/me/.pyenv/versions/3.9.11/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/me/.pyenv/versions/3.9.11/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/me/.reloadium/package/3.9/reloadium/__init__.py", line 4, in <module>
    pre_import_check()
  File "/Users/me/.reloadium/package/3.9/reloadium/__utils__.py", line 21, in pre_import_check
    import reloadium.corium
ImportError: dlopen(/Users/me/.reloadium/package/3.9/reloadium/corium.cpython-39-darwin.so, 0x0002): tried: '/Users/me/.reloadium/package/3.9/reloadium/corium.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/me/.reloadium/package/3.9/reloadium/corium.cpython-39-darwin.so' (no such file), '/Users/me/.reloadium/package/3.9/reloadium/corium.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

**Comment by dkrystki** [comment]
This issue has already been fixed.
Please upgrade to the newest plugin version (1.1.0).
Note that you may need to upgrade your PyCharm version to install this version
