### ISSUE TITLE
Fails to start debug with reloadium

### ISSUE THREAD

**Issue by aviadr1** [reloadware/reloadium#196]
## Describe the bug*
Tried debugging my project with reloadium pro. it fails
`Reloadium experienced a fatal error and has to quit.`

C:\Users\aviad\AppData\Local\pypoetry\Cache\virtualenvs\gv-TD9Xm0oY-py3.11\Scripts\python.exe -X pycache_prefix=C:\Users\aviad\AppData\Local\JetBrains\PyCharmCE2024.1\cpython-cache -m reloadium_launcher pydev_proxy "C:/Program Files/JetBrains/PyCharm Community Edition 2024.1.4/plugins/python-ce/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 57903 --file C:\Users\aviad\Documents\GitHub\gigaverse-ai\main.py run chat_analysis_persistence_service transcript_soundbite_service livestream_transcript_worker 
Connected to pydev debugger (build 241.18034.82)
(0.9104) Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
(0.9114) Machine: 
{'architecture': '64bit WindowsPE',
 'release': '10',
 'type': 'Windows',
 'version': '10.0.22631'}
(0.9134) Env:
{'RW_ACTIVEFILES': ';C:/Users/aviad/Documents/GitHub/gigaverse-ai/src/gv/ai/transcript_soundbite_service/soundbite.py',
 'RW_CACHE': 'True',
 'RW_DEBUG': 'True',
 'RW_DOCKER': 'False',
 'RW_EVENTSGRACEPERIOD': '0.7',
 'RW_FASTDEBUG_WHOLEPROJECT': 'False',
 'RW_IDE_NAME': 'PyCharm 2024.1.4',
 'RW_IDE_PLUGINVERSION': '1.5.1',
 'RW_IDE_SERVERPORT': '57902',
 'RW_IDE_TYPE': 'PyCharm',
 'RW_IDE_VERSION': '2024.1.4',
 'RW_LICENSEKEY': 'None',
 'RW_MERGEEVENTSPERIOD': '0.2',
 'RW_PAGERELOADONSTART': 'True',
 'RW_PARENTRUNID': 'None',
 'RW_PRINTLOGO': 'True',
 'RW_PROFILING_ENABLED': 'True',
 'RW_PROFILING_PARTIALS': 'True',
 'RW_QUICKCONFIG': '{"profiler":"Time","frame_scope":true,"cumulate_type":"Add","always_collect_memory":false,"error_handling_mode":"Always"}',
 'RW_REMOTE': 'False',
 'RW_SUBPROCESS': '0',
 'RW_USERID': 'None',
 'RW_VERBOSE': 'True',
 'RW_WATCHCWD': 'True',
 'RW_WATCHFILESWITHBREAKPOINTS': 'True'}
■■■■■■■■■■■■■■■■■■■
Reloadium Pro 1.5.1
■■■■■■■■■■■■■■■■■■■
If you like this project consider giving a star at https://github.com/reloadware/reloadium
(0.9334) Run id: a40ae521-d834-4ac2-be91-15483074c3d6
2024-07-05 23:32:22.346 | DEBUG    | gv.ai.common.settings:<module>:193 - Software Start Time
Traceback (most recent call last):
  File "C:\Users\aviad\.reloadium\package\3.11\reloadium\corium\lllll11ll11ll1l1Il1l1.py", line 189, in l1l11llll11llll1Il1l1
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\ll1l1111lll11ll1Il1l1.py", line 74, in exec_module
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\lll1ll1lll1l1l1lIl1l1\lll111l1ll1ll111Il1l1.py", line 694, in llll1lll1l111ll1Il1l1
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\l1ll1l1llll1l11lIl1l1\ll1l1111111ll11lIl1l1.py", line 584, in l11ll1lll111ll1lIl1l1
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\l1ll1l1llll1l11lIl1l1\ll1l1111111ll11lIl1l1.py", line 549, in ll1lllll1l1111l1Il1l1
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\ll1l1l1ll1111lllIl1l1\l1llll1lll111ll1Il1l1.py", line 426, in visit
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\ll1l1l1ll1111lllIl1l1\l1llll1lll111ll1Il1l1.py", line 451, in visit_Module
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\ll1l1l1ll1111lllIl1l1\l1llll1lll111ll1Il1l1.py", line 434, in generic_visit
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\ll1l1l1ll1111lllIl1l1\l1llll1lll111ll1Il1l1.py", line 426, in visit
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\ll1l1l1ll1111lllIl1l1\l1llll1lll111ll1Il1l1.py", line 505, in visit_Try
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\ll1l1l1ll1111lllIl1l1\l1llll1lll111ll1Il1l1.py", line 434, in generic_visit
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\ll1l1l1ll1111lllIl1l1\l1llll1lll111ll1Il1l1.py", line 426, in visit
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\ll1l1l1ll1111lllIl1l1\l1llll1lll111ll1Il1l1.py", line 466, in visit_ClassDef
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\ll1l1l1ll1111lllIl1l1\l1llll1lll111ll1Il1l1.py", line 434, in generic_visit
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\ll1l1l1ll1111lllIl1l1\l1llll1lll111ll1Il1l1.py", line 426, in visit
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\ll1l1l1ll1111lllIl1l1\l1llll1lll111ll1Il1l1.py", line 493, in visit_If
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\ll1l1l1ll1111lllIl1l1\l1llll1lll111ll1Il1l1.py", line 434, in generic_visit
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\ll1l1l1ll1111lllIl1l1\l1llll1lll111ll1Il1l1.py", line 426, in visit
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\l1ll1l1llll1l11lIl1l1\ll1l1111111ll11lIl1l1.py", line 59, in visit_FunctionDef
  File "D:\a\reloadware\reloadware\reload\package\__obfuscated__\reloadium\fast\l1ll1l1llll1l11lIl1l1\ll1l1111111ll11lIl1l1.py", line 355, in llllll1l11llll11Il1l1
IndexError: list index out of range
(1.3913) Critical reloader Error
{'traceback': 'Traceback (most recent call last):\n'
              "  File '.../reloadium\\corium\\lllll11ll11ll1l1Il1l1.py', line "
              '189, in l1l11llll11llll1Il1l1\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\ll1l1111lll11ll1Il1l1.py', "
              'line 74, in exec_module\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\lll1ll1lll1l1l1lIl1l1\\lll111l1ll1ll111Il1l1.py', "
              'line 694, in llll1lll1l111ll1Il1l1\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\l1ll1l1llll1l11lIl1l1\\ll1l1111111ll11lIl1l1.py', "
              'line 584, in l11ll1lll111ll1lIl1l1\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\l1ll1l1llll1l11lIl1l1\\ll1l1111111ll11lIl1l1.py', "
              'line 549, in ll1lllll1l1111l1Il1l1\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\ll1l1l1ll1111lllIl1l1\\l1llll1lll111ll1Il1l1.py', "
              'line 426, in visit\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\ll1l1l1ll1111lllIl1l1\\l1llll1lll111ll1Il1l1.py', "
              'line 451, in visit_Module\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\ll1l1l1ll1111lllIl1l1\\l1llll1lll111ll1Il1l1.py', "
              'line 434, in generic_visit\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\ll1l1l1ll1111lllIl1l1\\l1llll1lll111ll1Il1l1.py', "
              'line 426, in visit\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\ll1l1l1ll1111lllIl1l1\\l1llll1lll111ll1Il1l1.py', "
              'line 505, in visit_Try\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\ll1l1l1ll1111lllIl1l1\\l1llll1lll111ll1Il1l1.py', "
              'line 434, in generic_visit\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\ll1l1l1ll1111lllIl1l1\\l1llll1lll111ll1Il1l1.py', "
              'line 426, in visit\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\ll1l1l1ll1111lllIl1l1\\l1llll1lll111ll1Il1l1.py', "
              'line 466, in visit_ClassDef\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\ll1l1l1ll1111lllIl1l1\\l1llll1lll111ll1Il1l1.py', "
              'line 434, in generic_visit\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\ll1l1l1ll1111lllIl1l1\\l1llll1lll111ll1Il1l1.py', "
              'line 426, in visit\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\ll1l1l1ll1111lllIl1l1\\l1llll1lll111ll1Il1l1.py', "
              'line 493, in visit_If\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\ll1l1l1ll1111lllIl1l1\\l1llll1lll111ll1Il1l1.py', "
              'line 434, in generic_visit\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\ll1l1l1ll1111lllIl1l1\\l1llll1lll111ll1Il1l1.py', "
              'line 426, in visit\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\l1ll1l1llll1l11lIl1l1\\ll1l1111111ll11lIl1l1.py', "
              'line 59, in visit_FunctionDef\n'
              '  File '
              "'D:\\a\\reloadware\\reloadware\\reload\\package\\__obfuscated__\\reloadium\\fast\\l1ll1l1llll1l11lIl1l1\\ll1l1111111ll11lIl1l1.py', "
              'line 355, in llllll1l11llll11Il1l1\n'
              'IndexError: list index out of range\n'}
Reloadium experienced a fatal error and has to quit.
To see the exception run Reloadium with environmental variable RW_DEBUG=True
Please submit a github issue to let us know at https://github.com/reloadware/reloadium

**Comment by dkrystki** [comment]
Hey @aviadr1 
Thanks for submitting this.
Reloadium couldn't parse one of the files. 
Somehow one of the function in AST of the source code has empty body. The weird part is that I added a check for this.
I'll try to reproduce it. If not I'll add a more detailed error message with offending line so it's easier to find.
