### ISSUE TITLE
Reloadium on pycharm won't load Flask templates

### ISSUE THREAD

**Issue by pommepommee** [reloadware/reloadium#20]
**Describe the bug**
I tried the reloadium plugin for PyCharm for my Flask project. The problem is reloadium cannot found the index.html template used in my project. 

Here is the error : 
```
C:\Users\tom52\Desktop\projet>reloadium run app.py
■■■■■■■■■■■■■■■
Reloadium 0.8.8
■■■■■■■■■■■■■■■
If you like this project consider becoming a sponsor or giving a start at https://github.com/reloadware/reloadium
 * Serving Flask app '__main__' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)

Loaded 3 watched modules so far from paths:
 - \C:\Users\tom52\Desktop\projet\**\*.html
 - \C:\Users\tom52\Desktop\projet\**\*.py

ERROR:__main__:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\reloadium\reloader\llll11l1l1l1l1llIl1l1\llllll1l1ll111l1Il1l1.py", line 165, in ll11ll1ll11ll111Il1l1
  File "C:\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\tom52\Desktop\projet\app.py", line 28, in index
    return render_template('index.html', history=history)
  File "C:\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Python310\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Python310\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
INFO:werkzeug:127.0.0.1 - - [06/Jun/2022 22:24:08] "GET / HTTP/1.1" 500 -
```

**To Reproduce**
1. Create a python flask project with the following files tree:
```
project/
      | app.py
      | templates/
          | index.html
```
 
3. Create a templates directory and add index.html
4. create the app in python with `app = Flask(__name__, template_folder='templates')` and `app.run()`
5. run `reloadium run app.py`

**Expected behavior**
As the Flask constructor specifies the template folder, the flask app should run correctly

**Screenshots**
- Running the code by python app.py or PyCharm (same result)
![image](https://user-images.githubusercontent.com/28791624/172242269-b56f39f0-e201-480a-9add-db4dc92f94cd.png)

- Running the code with console reloadium or pycharm reloadium (same result)
![image](https://user-images.githubusercontent.com/28791624/172242563-201f9367-d8db-4f7a-ba89-0b415358c378.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS version: Windows 11 Professional - Version 21H2 - build 22000.675
 - Reloadium package version: 0.8.8
 - PyCharm plugin version: 0.8.2
 - Editor: PyCharm 
 - Run mode: Run & Debug

**Additional context**

**Comment by pommepommee** [comment]
If I may add a point, the command `reloadium run -m flask run` works fine, but if you want to pass arguments to your python scripts and get it from a function `if __name__ == '__main__'`, the script won't go through it and just load the flask app.
