### ISSUE TITLE
Does not install directly from uv

### ISSUE THREAD

**Issue by eevleevs** [reloadware/reloadium#204]
## Describe the bug
`reloadium.corium` is not found when running from uv

## To Reproduce
Install https://docs.astral.sh/uv/getting-started/installation/

```
~\test> uv venv --python 3.11                                                                                          05 Nov 2024 19:00:59
Using CPython 3.11.10
Creating virtual environment at: .venv
Activate with: overlay use .venv/Scripts/activate.nu
~\test> uv pip install reloadium --python 3.11                                                                         05 Nov 2024 19:01:04
Resolved 1 package in 8ms
Installed 1 package in 42ms
 + reloadium==1.5.1
~\test> uv run reloadium --python 3.11                                                                                 05 Nov 2024 19:01:10
It seems like your platform or Python version are not supported yet.
Windows, Linux, macOS and Python 64 bit >= 3.8 (>= 3.9 for M1) <= 3.11 are currently supported.
Please submit a github issue if you believe Reloadium should be working on your system at
https://github.com/reloadware/reloadium
To see the exception run Reloadium with environmental variable RW_DEBUG=True
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\giuli\test\.venv\Scripts\reloadium.exe\__main__.py", line 5, in <module>
  File "C:\Users\giuli\test\.venv\Lib\site-packages\reloadium\__init__.py", line 4, in <module>
    pre_import_check()
  File "C:\Users\giuli\test\.venv\Lib\site-packages\reloadium\__utils__.py", line 24, in pre_import_check
    import reloadium.corium
ModuleNotFoundError: No module named 'reloadium.corium'
```

## Expected behavior
```
~\test> uv run reloadium --python 3.11                                                                                 05 Nov 2024 19:01:10
No command provided
```

## Desktop or remote (please complete the following information):
 - OS: Windows
 - OS version: 11
 - M1 chip: no
 - Reloadium package version: 1.5.1
 - PyCharm plugin version: none
 - Editor: none
 - Python Version: 3.11.10
 - Python Architecture: 64bit
 - Run mode: Debug

**Comment by eevleevs** [comment]
Works though by installing directly the windows whl file through `uv add --dev https://files.pythonhosted.org/packages/3a/49/498308ace2816d6bd90b9afaac9b835666c95369945b13f7c26d7e0d923c/reloadium-1.5.1-cp311-cp311-win_amd64.whl`
