### ISSUE TITLE
PYENV not recognized as current Python Version

### ISSUE THREAD

**Issue by mctinker** [reloadware/reloadium#42]
**Describe the bug**
I have the PyCharm interpreter pointing to /pyenv/versions/3.10.6/bin/python3.10, but when I try to run Reloadium it tells me that my version of Python is not yet supported:

/Users/mikrubin/.pyenv/versions/3.10.6/bin/python3.10 -m reloadium pydev_proxy /Applications/Tools/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py --multiprocess --save-signatures --qt-support=auto --client 127.0.0.1 --port 52169 --file /Users/mikrubin/My Drive/Python/MapTasker.py 
It seems like your platform or Python version are not supported yet.
Windows, Linux, macOS and Python >= 3.7 (3.9 for M1) are currently supported.
Please submit a github issue if you believe Reloadium should be working on your system at

**To Reproduce**
1. Use Pyenv to manage Python 3.10
2. Bring up Pycharm and point its interpreter to the above.
3. Run reloadium plugin

**Expected behavior**
Normal reloadium debugging.

**Screenshots**
See above, under '... is not yet supported:'

**Desktop (please complete the following information):**
 - OS: OS X 
 - OS version: 12.6
 - Reloadium package version: None
 - PyCharm plugin version: 0.8.5
 - Editor: PyCharm
 - Run mode: Debug via Reloadium

**Additional context**

**Comment by dkrystki** [comment]
Does it work when you install reloadium with `pip install reloadium` and run it from the terminal (`reloadium run my_script.py`)`?

**Comment by mctinker** [comment]
I did as you said, and yes, reloadium runs fine.

**Comment by mctinker** [comment]
Yes, it still fails.  It has got to be something on my end and I am trying different settings/configurations in an effort to identify what is wrong.  Thanks for checking.

**Comment by dkrystki** [comment]
@mctinker 
I believe this is related to this issue https://github.com/reloadware/reloadium/issues/57
Could you follow the instructions I have provided there?

**Comment by mctinker** [comment]
So I've since upgraded from Python 3.10.7 to 3.10.8.  With this upgrade, I also had to update reloadium.  With this update I get[ this error](https://imgur.com/17enK1b) when running reloadium from the command line.

**Comment by dkrystki** [comment]
@mctinker That will be fixed in the next release.
Is the initial issue ("Python is not yet supported" error) resolved when running on PyCharm?
Also are you an M1 chip user?

**Comment by mctinker** [comment]
Yes, I still encounter the original error.  I am on a 2020 Intel i9 Mac running Monterey 12.6.1 .  Let me know if I can provide any further details.

**Comment by dkrystki** [comment]
Reloadium plugin installs reloadium package to <home>/.reloadium/package directory, could you verify whether this directory exists and contains a package for the python version you are using?
If not could you please reinstall the plugin and submit the idea.log file?

If the package is correctly installed could you go to `<home>/.reloadium/package/<python version>/reloadium` and add the following lines at the beginning of the __init__.py file?

```
import sys
print(sys.path)
```
Also please set `RW_DEBUG` environmental variable to `True`
Then run your script using the Reloadium plugin and paste the output here?

**Comment by mctinker** [comment]
I don't know where to put the RW_DEBUG = TRUE, but here is the output when running from console:

mikrubin@Michaels-iMac ~/M/Python [1]> pyenv version
3.10.8 (set by /Users/mikrubin/My Drive/Python/.python-version)
mikrubin@Michaels-iMac ~/M/Python> reloadium -h
['/Users/mikrubin/.pyenv/versions/3.10.8/bin', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python310.zip', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/lib-dynload', '/Users/mikrubin/.local/lib/python3.10/site-packages', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages']
['/Users/mikrubin/.pyenv/versions/3.10.8/bin', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python310.zip', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/lib-dynload', '/Users/mikrubin/.local/lib/python3.10/site-packages', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages']
INFO
  version      0.9.4

COMMANDS
  help/-h      Shows this help
  run          Runs a python file. Add -m to run a module.
mikrubin@Michaels-iMac ~/M/Python> reloadium run MapTasker.py
['/Users/mikrubin/.pyenv/versions/3.10.8/bin', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python310.zip', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/lib-dynload', '/Users/mikrubin/.local/lib/python3.10/site-packages', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages']
['/Users/mikrubin/.pyenv/versions/3.10.8/bin', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python310.zip', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/lib-dynload', '/Users/mikrubin/.local/lib/python3.10/site-packages', '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages']
Traceback (most recent call last):
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/ll1l1lll1l1lll1lIl1l1.py", line 138, in l11l1llll1llll11Il1l1
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/l1111l1l111ll1llIl1l1.py", line 326, in llllll1111llll11Il1l1
  File "<string>", line 4, in __init__
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/l1111l1l111ll1llIl1l1.py", line 242, in __post_init__
  File "<string>", line 5, in __init__
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/l1l1l1llll11lll1Il1l1.py", line 170, in __post_init__
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/l1l1l1llll11lll1Il1l1.py", line 248, in l1lll1llllll11l1Il1l1
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/lllllll111l1l1llIl1l1.py", line 389, in l11l1llll1lll111Il1l1
  File "<string>", line 12, in __init__
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/lllllll111l1l1llIl1l1.py", line 332, in __post_init__
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/vendored/watchdog/observers/api.py", line 291, in schedule
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/vendored/watchdog/observers/kqueue.py", line 450, in __init__
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/vendored/watchdog/utils/dirsnapshot.py", line 251, in __init__
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/vendored/watchdog/utils/dirsnapshot.py", line 283, in walk
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/vendored/watchdog/utils/dirsnapshot.py", line 283, in walk
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/vendored/watchdog/utils/dirsnapshot.py", line 283, in walk
  [Previous line repeated 4 more times]
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/vendored/watchdog/utils/dirsnapshot.py", line 259, in walk
OSError: [Errno 24] Too many open files: '/Users/mikrubin/My Drive/Python/venv/lib/python3.10/site-packages/pip/_internal/vcs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mikrubin/.pyenv/versions/3.10.8/bin/reloadium", line 9, in <module>
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/__init__.py", line 21, in start
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/l1111l1l111ll1llIl1l1.py", line 612, in start
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/l1111l1l111ll1llIl1l1.py", line 596, in l1llll11ll11ll1lIl1l1
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/l1111l1l111ll1llIl1l1.py", line 502, in l1l1lll11ll1ll1lIl1l1
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/l1111l1l111ll1llIl1l1.py", line 325, in llllll1111llll11Il1l1
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/contextlib.py", line 153, in __exit__
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/ll1l1lll1l1lll1lIl1l1.py", line 143, in l11l1llll1llll11Il1l1
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/ll1l1lll1l1lll1lIl1l1.py", line 107, in l11ll1111lll11llIl1l1
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/l1l1l111l1l111l1Il1l1.py", line 15, in l111ll11lll11l11Il1l1
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/l1l1l111l1l111l1Il1l1.py", line 43, in ll1ll1l1111l1ll1Il1l1
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/l1l1l111l1l111l1Il1l1.py", line 15, in l111ll11lll11l11Il1l1
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/corium/l1l1l111l1l111l1Il1l1.py", line 24, in lll11ll1l1l111l1Il1l1
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/vendored/sentry_sdk/hub.py", line 105, in _init
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/vendored/sentry_sdk/client.py", line 85, in __init__
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/vendored/sentry_sdk/client.py", line 119, in _init_impl
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/vendored/sentry_sdk/integrations/__init__.py", line 93, in setup_integrations
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/vendored/sentry_sdk/integrations/__init__.py", line 41, in iter_default_integrations
  File "/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1548, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1591, in _fill_cache
OSError: [Errno 24] Too many open files: '/Users/mikrubin/.pyenv/versions/3.10.8/lib/python3.10/site-packages/reloadium/vendored/sentry_sdk/integrations'
mikrubin@Michaels-iMac ~/M/Python [1]>

**Comment by dkrystki** [comment]
Add it in your Run/Debug configuration like shown below and run a script in pycharm.
![2022-11-13_10:42:21](https://user-images.githubusercontent.com/45499236/201500234-92f0a21a-1c4e-4fb6-a3dd-4166517d2627.png)

**Comment by mctinker** [comment]
Ok, I added the RW_DEBUG=True and after getting the reloadium platform unsupported error, the debug window displays: "Connection to Python debugger failed: Socket closed" .  No other visible output was generated.

**Comment by dkrystki** [comment]
What happens when you use it the run mode instead of debug?

**Comment by mctinker** [comment]
Ok, I just updated reloadium to 0.9.0 and it now works fine!  I don't know what changed but the problem has disappeared.  I am closing the problem.  Thank you for your attention!!!
