### ISSUE TITLE
Errors when using pycharm+flask+flask_sqlalchemy

### ISSUE THREAD

**Issue by kristaller486** [reloadware/reloadium#77]
## Describe the bug
When I try to run a flask application with the flask-sqlalchemy module an error occurs. Without reloadium everything works fine. 
 - flask: 2.2.2
 - flask-sqlalchemy: 3.0.2
## To Reproduce
1) Run in pycharm example from https://github.com/pallets-eco/flask-sqlalchemy#a-simple-example

## Desktop (please complete the following information):**
 - OS: Windows
 - OS version:  [Version 10.0.19044.2251]
 - Reloadium package version: 0.9.6
 - PyCharm plugin version: 0.9.1
 - Editor: PyCharm
 - Python Version: 3.10
 - Python Architecture: 64bit
 - Run mode: Run

## Additional context
```
Traceback (most recent call last):
  File "F:\foldername\test.py", line 6, in <module>
    db = SQLAlchemy(app)
  File "C:\Users\Kristaller\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_sqlalchemy\extension.py", line 219, in __init__
    self.init_app(app)
  File "C:\Users\Kristaller\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_sqlalchemy\extension.py", line 320, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "C:\Users\Kristaller\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_sqlalchemy\extension.py", line 606, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "C:\Users\Kristaller\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\create.py", line 743, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "C:\Users\Kristaller\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "C:\Users\Kristaller\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\create.py", line 636, in create_engine
    raise TypeError(
TypeError: Invalid argument(s) 'echo' sent to create_engine(), using configuration SQLiteDialect_pysqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
```

**Comment by dkrystki** [comment]
Fixed in reloadium 0.9.7 and PyCharm plugin 0.9.2
