### ISSUE TITLE
Not working, Python 3.10.8, Reloadium 0.9.2 plugin version, M2 chip

### ISSUE THREAD

**Issue by stormnick** [reloadware/reloadium#84]
## Describe the bug*
Trying to run using reloadium after the latest update results in the issue:

`It seems like your platform or Python version are not supported yet.
Windows, Linux, macOS and Python 64 bit >= 3.7 (>= 3.9 for M1) <= 3.10 are currently supported.
Please submit a github issue if you believe Reloadium should be working on your system at
https://github.com/reloadware/reloadium
To see the exception run reloadium with environmental variable RW_DEBUG=True`

## To Reproduce
1. Start any code with reloadium using latest versions using Python 3.10.8 and M2 chip
2. Get the error

## Expected behavior
For it to work.

## Desktop or remote (please complete the following information):**
 - OS: Mac
 - OS version: 12.6
 - M1 chip: Kinda?, M2 chip
 - Reloadium package version: 0.9.7
 - PyCharm plugin version: 0.9.2
 - Editor: PyCharm 2022.3.1 (build 223.8214.51)
 - Python Version: 3.10.8
 - Python Architecture: 64bit
 - Run mode: Both

## Additional context
Worked before the latest 0.9.2 plugin update (or maybe before the latest PyCharm update).

Running with `os.environ["RW_DEBUG"] = "True"` does not present any extra output. Am I setting the environmental variable wrong?

**Comment by dkrystki** [comment]
Could you set that variable in PyCharm like shown in the screenshot and try again?

![2023-01-20_12:01:14](https://user-images.githubusercontent.com/45499236/213602510-4d10f2f2-c11c-4f9d-ab4a-9b75fa484224.png)

**Comment by stormnick** [comment]
Thanks for the screenshot. Here is the output:

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/Users/storm/.reloadium/package/3.7/reloadium/__init__.py", line 4, in <module>
    pre_import_check()
  File "/Users/storm/.reloadium/package/3.7/reloadium/__utils__.py", line 21, in pre_import_check
    import reloadium.corium
ModuleNotFoundError: No module named 'reloadium.corium'`

**Comment by dkrystki** [comment]
I believe it's related to https://github.com/reloadware/reloadium/issues/78 
Could you recreate your python interpreter and try again?

**Comment by stormnick** [comment]
Well, the error is different now. Am I stupid and doing something wrong :(? I tried to recreate the python interpreter twice + tried to reinstall the plugin and the module. I keep getting this error now: 

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/Users/storm/.reloadium/package/3.10/reloadium/__init__.py", line 4, in <module>
    pre_import_check()
  File "/Users/storm/.reloadium/package/3.10/reloadium/__utils__.py", line 21, in pre_import_check
    import reloadium.corium
ImportError: dlopen(/Users/storm/.reloadium/package/3.10/reloadium/corium.cpython-310-darwin.so, 0x0002): tried: '/Users/storm/.reloadium/package/3.10/reloadium/corium.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))`

**Comment by dkrystki** [comment]
Could you run this command in the terminal and send what it returns?
`sysctl -n machdep.cpu.brand_string`

**Comment by stormnick** [comment]
Yes, sure, it reads
`Apple M2`

**Comment by yuanhaozuogenius** [comment]
> Could you run this command in the terminal and send what it returns? `sysctl -n machdep.cpu.brand_string`

I met a similar error below:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/Users/barry/.reloadium/package/3.10/reloadium/__init__.py", line 4, in <module>
    pre_import_check()
  File "/Users/barry/.reloadium/package/3.10/reloadium/__utils__.py", line 21, in pre_import_check
    import reloadium.corium
ImportError: dlopen(/Users/barry/.reloadium/package/3.10/reloadium/corium.cpython-310-darwin.so, 0x0002): tried: '/Users/barry/.reloadium/package/3.10/reloadium/corium.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/barry/.reloadium/package/3.10/reloadium/corium.cpython-310-darwin.so' (no such file), '/Users/barry/.reloadium/package/3.10/reloadium/corium.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))


and the command outputted "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz"

Is it a bug? Orz @dkrystki

**Comment by dkrystki** [comment]
@yuanhaozuogenius What's your plugin version?

**Comment by yuanhaozuogenius** [comment]
> @yuanhaozuogenius What's your plugin version?

0.91 on my MacBook and PyCharm version is PyCharm 2021.1.2 (Professional Edition). And 0.91 is still available in  Marketplace. Is it caused by the old Pycharm version? @dkrystki

**Comment by dkrystki** [comment]
@yuanhaozuogenius You will have to update the plugin to the newest version for this bug to be fixed.

**Comment by dkrystki** [comment]
@yuanhaozuogenius To update to the newest plugin version you will also have to upgrade your PyCharm.

**Comment by yuanhaozuogenius** [comment]
Gotcha, thanks man.
